SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone ="+0:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    role INT NOT NULL,
    passkey VARCHAR(100) NOT NULL
);